### ISSUE TITLE
can't add dream box to HomeKit 

### ISSUE THREAD

**Issue by Alex7802** [mdaskalov/homebridge-dreambox#17]
HI! 
Trying to add 2 dm800 to HomeKit and got error:
unable to add accessory. Accessory is out of compliance.
Other homebridge devices work fine. 
Config
{
            "platform": "Dreambox",
            "devices": [
                {
                    "name": "DreamLiveroom",
                    "hostname": "192.168.1.82"
                },
                {
                    "name": "DreamBadroom",
                    "hostname": "192.168.1.61"
                }
            ]
        },
 log doesn't have any errors. help!

**Comment by mdaskalov** [comment]
It works for me - I've just tried it. 
Could be that there is a problem with the cache.

The latest version of the [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x) (v4.28.0) could delete the cache entry for single device or all devices or completely reset the configuration.

You have to add each dreambox devices using the code in the log file. There are also separate ports for each dreambox device assigned (see them in the log). Make sure that these ports are accessible from your mobile.

**Comment by Alex7802** [comment]
I deleted cache of devices.. but no change. 
[10/5/2020, 7:57:49 PM] DreamLiveroom2 is running on port 42689.
[10/5/2020, 7:57:49 PM] Please add [DreamLiveroom2] manually in Home app. Setup Code: 031-45-888
[10/5/2020, 7:57:49 PM] DreamBadroom2 is running on port 45945.
[10/5/2020, 7:57:49 PM] Please add [DreamBadroom2] manually in Home app. Setup Code: 031-45-888
[10/5/2020, 7:57:50 PM] [Dreambox] Device: 192.168.1.82, prepareTvService
[10/5/2020, 7:57:50 PM] [Dreambox] Device: 192.168.1.82, prepereTvSpeakerService
[10/5/2020, 7:57:51 PM] [Dreambox] Device: 192.168.1.82, prepareTvInputServices
[10/5/2020, 7:57:51 PM] [Dreambox] Device: 192.168.1.61, prepareTvService
[10/5/2020, 7:57:51 PM] [Dreambox] Device: 192.168.1.61, prepereTvSpeakerService
[10/5/2020, 7:57:51 PM] [Dreambox] Device: 192.168.1.61, prepareTvInputServices
[10/5/2020, 7:57:56 PM] [Dreambox] TypeError: bouquet.e2servicelist.e2service.forEach is not a function
    at /usr/lib/node_modules/homebridge-dreambox/dreambox-accessory.js:193:45
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Phone (IOS 14.0.1) has IP 192.168.1.39. All ports accessible..  No firewall, etc..

**Comment by Alex7802** [comment]
I roll back to 0.4.5 version and can add devices to my home. All work on 0.4.5. When I update to next or current version all dream box in HomeKit not responding. Dreambox DM800.

**Comment by mdaskalov** [comment]
In your previous message there is an error in line 193 of dreambox-accessory. Could be that there is no favorites bouquet. Create bouquet with few channels and configure the plugin to use the new bouquet.

There are no significant changes between 0.4.5 and 0.4.6 - only that mqtt was added. So I really have no clue, how to reproduce your situation. If there are errors in the log please post them here, so I can have a look and fix it.

I am now preparing a new release, where channels can be configured as separate buttons. I will also rewrite the platform initialization and caching - maybe this will also fix your problem.

**Comment by Alex7802** [comment]
I added bouquet. No errors in log. Still stay on 0.4.5, if update version, device no response

**Comment by mdaskalov** [comment]
Hi Alex, 
I've published the new version yesterday. Could you try if your problem is now solved? You will have to reconfigure both devices. Delete unused devices from cache using the config UI.

**Comment by Alex7802** [comment]
Just updated to last version. No errors in log, looks fine in homebridge, but can't add device to HomeKit. IOS 14.
From Config UI X I can power on/off device. I made reset homebridge/ remove pair data - no help.  Still cccessory is out of compliance. 
I found same issue from other plugin, please look:
https://github.com/chrisjshull/homebridge-nest/commit/2a854a33f95a084159f50b1fb6deee11dff7e3b5

**Comment by Alex7802** [comment]
I made small patch
root@raspberrypi:~# diff /usr/lib/node_modules/homebridge-dreambox/dreambox-accessory.js /root/dreambox-accessory.js 
36c36
<       .setCharacteristic(Characteristic.SerialNumber, this.dreambox.serialNumber || 'None')
---
>       .setCharacteristic(Characteristic.SerialNumber, this.dreambox.serialNumber)
159c159
< module.exports = DreamboxAccessory;
and its work! thank you

**Comment by mdaskalov** [comment]
This could mean, that the `getDeviceInfo` call is not completed when `setCharacteristic` is. called. Maybe the `responseDelay` is too less in your case. What kind of hardware do you use? I have raspberry pi 2 as server.
I will remove this timeout and provide defaults for all key characteristics in next release.

**Comment by mdaskalov** [comment]
I've removed the delay timeout and the serial number is set after the data is fetched from the box.
Could you confirm, that the problem is solved in the new release (v1.1.0)?

**Comment by mdaskalov** [comment]
This should be solved in v1.1.0
